HTTP_SERVICE_PORT: "8080"
GRPC_SERVICE_PORT: "5000"
OMDB_API_KEY: "faf7e5bb"
OMDB_API_BASE_URL: "http://www.omdbapi.com/"

MYSQL_USERNAME: "root"
MYSQL_PASSWORD: "12345"
MYSQL_HOST: "127.0.0.1"
MYSQL_PORT: "3306"
MYSQL_DBNAME: "omdb-server"
